# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26fee4b533e9e1540a8dc32c4ad3a4a828c923ab623af6dea58a36ec3ed94ef60c27f2158a343b217f36b372bf16a60272744550adfe2589cef670e2bfc73dfb

test:
  secret_key_base: c21ab1b5b8bbe8501ba21410da4c2fe932bbcdec83b8a57329fba8b365a1946c887d46a89ecfe20898daaffe3c0dc9be058a3bc47fa23f6381dc1c372d660706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
